\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename ggadt.info
@include version.texi
@settitle GGADT @value{VERSION}

@c Define a new index for options.
@defcodeindex op
@c Combine everything into one index (arbitrarily chosen to be the
@c concept index).
@syncodeindex op cp
@c %**end of header

@copying
This manual is for GGADT (version @value{VERSION}, @value{UPDATED}),
which calculates scattering properties of dust grains in the interstellar
medium by using anomalous diffraction theory (ADT). 

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts.  A copy of the license is included in the section entitled
``GNU Free Documentation License''.
@end quotation
@end copying
@c If your manual is published on paper by the FSF, it should include
@c the standard FSF Front-Cover and Back-Cover Texts, as given in
@c maintain.texi.

@dircategory Basics
@direntry
* GGADT: (ggadt).        
@end direntry

@titlepage
@title GGADT
@subtitle for version @value{VERSION}, @value{UPDATED}
@author John Hoffman (@email{jah5@@princeton.edu}), Michael Tarczon (@email{mtarczon@@princeton.edu})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents


@ifnottex

@node Top
@top GGADT
This manual is for GGADT (version @value{VERSION}, @value{UPDATED}),
which calculates scattering properties of dust grains in the interstellar
medium by using anomalous diffraction theory (ADT). 
@end ifnottex

@menu
* Overview::		General purpose and information.
* Installation::	How to install @command{ggadt} on your system.
* Invoking GGADT::	Giving @command{ggadt} your input.	
* Example usage::	Quick examples to get you started.
* Testing against previous results::  Comparing GGADT to existing literature
* FFT comparison::		Comparison between GPFA and FFTW3 timing.
* GNU Free Documentation License:: Copying and sharing this documentation.
* Concept index::	Index of concepts.
@end menu


@node Overview
@chapter Overview

@cindex greetings
@cindex overview

GGADT stands for General Geometry Anomalous Diffraction Theory, and is Fortran 95 compliant. GGADT allows a user to specify a custom dust geometry (either a spheroid, sphere, or an agglomerate of spheres), and calculates either the differential scattering cross section as a function of scattering angle, or the energy-dependent absorption and scattering cross sections. Anomalous diffraction theory is valid when @math{ka_{eff} \lesssim 1}, where @math{k} is the wavenumber of the incident photon, and @math{a_{eff}} is the ``effective radius" of the grain, defined to be the radius of a sphere that has the same volume as the grain.

@cindex authors
@cindex Hoffman, John
@cindex Tarczon, Michael
GGADT was written by John Hoffman and Michael Tarczon.



@section Background
@cindex background
@cindex interstellar medium
@cindex astrophysics

@subsection Dust in the interstellar medium (ISM)

The interstellar medium (ISM) refers to everything that occupies the space between stars in a galaxy. The ISM of the Milky Way contains rich physics and is an active area of astrophysical research. Dust, molecules, gas, radiation, cosmic rays -- all of these are important constituents of the ISM, and all of these constituents play roles of varying dyanmical importance, depending on the local ISM environment in question.@footnote{Draine, Bruce T., Physics of the Interstellar and Intergalactic Medium, 2011, Princeton University Press, NJ.}.

One area of active research in ISM physics is determining the size distribution and composition of interstellar dust. One way to probe the size distributions and dust composition is by measuring how ISM dust interacts with x-ray radiation.@footnote{Overbeck, J.W. 1965, ApJ, 141, 864}@footnote{Hayakawa, S. 1970, Prog. Theor. Phys., 43, 1224}@footnote{Martin, P.G. 1970, MNRAS, 149, 221} When looking at an x-ray source through interstellar dust, the scattering properties of the intermediate dust create an x-ray ``halo'' around the source.@footnote{Draine, B.T. 2003, ApJ, 598, 1026}.

GGADT is designed to be a tool to test dust models against observations of x-ray halos. Since the size of a typical dust grain (0.1 micrometers) is large compared to typical x-ray wavelengths (1 nanometer), an approximation known as Anomalous Diffraction Theory (ADT)@footnote{van de Hulst H., Light scattering by small particles, 1957, J.Wiley & Sons, NY.} can be used to calculate the absorption and scattering properties of dust grains@footnote{Draine, B.T. and Allaf-Akbari, K. 2006, ApJ, 652, 1318}.

@subsection Anomalous Diffraction Theory (ADT)

The mathematics of what GGADT does is best explained in Draine and Allaf-Akbari 2006; we include a portion of that paper below.
@quotation

At X-ray energies materials have refractive indices very close to unity (|m - 1| << 1), and the dust grains responsible for most of the scattering are usually much larger than the wavelength of the incoming radiation (ka >> 1 [k is the wavenumber of the incident radiation, a is the effective radius of the grain]). In this regime, the scattering and absorption of X-rays can be calculated using an approximation first developed by van de Hulst (1957) and known as anomalous diffraction theory (ADT). ADT is a combination of ray-tracing optics (applicable because k*a >> 1) and Huygens' principle of propagation of a scalar field, applied to cases in which the electromagnetic wave can enter and propagate through the grain with essentially no reflection or refraction (|m - 1| << 1).

Consider an incident plane wave @math{U_{inc} = U_0\exp(ikz)}, propagating in the z-direction. Under the conditions above, the plane wave, once reaching a plane V located just beyond the grain and normal to the direction of the propagation of the incident wave, will have changed by a fractional amount that we refer to as the @emph{shadow function}, @math{f(x,y)}: 

@math{f(x,y) = 1-\phi(x,y)}

where the complex phase function phi is 

@math{\phi(x,y) = k\int_{-\infty}^{\infty}[1-m(x,y,z)]dz}

where @math{m(x,y,z)} is the refractive index at the point @math{(x,y,z)}.

Once the shadow function is known, Huygens' principle allows the amplitude of the scattered part of the wave, in the radiation zone, to be calculated as a Fourier transform of the shadow function over the plane V: 


@math{U_{sca}(r\vec{n}) = U_0\frac{\exp{(ikr)}}{kr}S(\vec{n})}@*
@math{S(\vec{n}) = S(k_x, k_y) = \frac{k^2}{2\pi}\int \exp{[i(k_xx+k_yy)]}f(x,y)dxdy}@*
@math{k_x = k(\vec{n}\cdot\vec{x})}@*
@math{k_y = k(\vec{n}\cdot\vec{y})}@*

The scattering properties of the grain can be obtained from @math{S(\vec{n})}, with the differential scattering cross section given by 

@math{\frac{d\sigma_{sca}}{d\Omega}(\vec{n}) = \frac{|S(\vec{n})|^2}{k^2}}

 @author Draine and Allaf-Akbari 2006
@end quotation

@section Basic GGADT logic outline

GGADT does the following:

@enumerate

@item Reads in dust and x-ray parameters
@item For each of the @option{nangle} orientations (and @option{nephots} photon energies, if the total cross section is being calculated),
@enumerate
@item Calculate the shadow function of the grain on a 2D grid
@item If calculating the differential scattering cross section:
@itemize
@item Take the centered FFT of this grid using FFTW
@item Normalize this result so that it represents @math{dQ_{scat}/d\Omega}, i.e., the differential scattering cross section divided by @math{\pi a^2}.
@item Add contribution of differential cross-section to orientational average
@end itemize
@item If calculating the total cross sections:
@itemize
@item Calculate the cross sections from the shadow function for the given orientation (and photon energy)
@item Add contribution of this orientation to the average cross section at the given photon energy
@end itemize
@end enumerate

@item Output orientationally averaged grid (if calculating differential scattering cross section) or the energy dependent absorption and scattering cross sections.

@end enumerate


@node Installation
@chapter Installation

@cindex installing
@cindex configure
@cindex enable-openmp
@cindex gcc 

@section System requirements
GGADT should install easily on most @emph{Unix-based systems} (e.g. Linux, Mac) by following the standard GNU install procedures, described in @file{INSTALL}.

@example
./configure [--enable-openmp] [--enable-fftw3] @dots{}
make
@end example

The @code{ggadt} binary is now located in the @code{src} directory. An optional next step is to do @code{make install}, which installs the ggadt into a globally-accessible folder (usually @code{/usr/local/bin}). If you would like to do this, fine, but we prefer a more self-contained setup. We will assume for the remainder of the documentation that you did @emph{not} do a @code{make install}.

If you did do @code{make install}, you can undo it by running @code{make uninstall}. To clean and remake GGADT, simply do @code{make clean} and then @code{make}.

We haven't tested any speed improvements, but it might be advantageous to also add compiler optimization to the compilation, e.g. 

@example
./configure FCFLAGS="-O3" [--enable-openmp] [--enable-fftw3] @dots{}
@end example


@section Package dependencies

If you would like to use a particular Fortran compiler, you may specify one by adding @code{FC=/path/to/compiler} to the @code{configure} arguments.

@itemize @bullet

@item @strong{Suitable C and Fortran compilers}: GGADT was developed using the GNU compiler suite (version 4.5.4 and higher) throughout, but the @code{configure} script will try to work with most common compilers. GGADT has been tested to compile on versions 4.3 and later of gfortran. If you experience any compilation problems, please let John Hoffman know!

@item (@emph{Optional}) @strong{FFTW 3}. Available at @url{http://www.fftw.org/}. FFTW3 is NOT required (or currently supported, but will be in the next version). 
@itemize @minus

@item @emph{Location of the FFTW3 headers}: In order for GGADT to find the Fortran headers for FFTW3, they must be in the standard location (@code{/usr/local/include} or @code{usr/include}) or in @code{$prefix/include} where @code{$prefix} is defined by doing @code{./configure --prefix=<prefix>} at the configuration step for @code{ggadt}. If you have FFTW3 installed with MacPorts, the configure script should be able to find it for you, and you don't have to specify anything extra.

@end itemize



@itemize @minus

@item @strong{OpenMP}: For the OpenMP version of GGADT, you must have C and Fortran compilers that are compatible with OpenMP version 4.0. 

@end itemize

@item @strong{Mac users}
@itemize @minus

@item Install the latest edition of @strong{XCode command-line tools}. As of Mac OSX v10.9.1, the command-line tools are not included in XCode automatically, so you have to do this on your own.
@item @strong{Macports} is highly recommended. It provides a convenient, safe package manager for Mac (unofficial, of course). To set up an environment condusive to compiling and running @code{ggadt}, do the following from the terminal:
@enumerate
@item Download and install macports from @url{http://www.macports.org/}.
@item Install gcc (4.5.4 or higher is recommended), and the FFTW3 library if you want:
@example
sudo port install gcc45
sudo port install fftw-3 (optional)
@end example
@item Set the gcc compiler: @code{sudo port select --set gcc mp-gcc45}
@end enumerate
@end itemize
@item (@emph{Optional}) @strong{Python 2.7} or later for some of the included scripts.
@item (@emph{Optional}) @strong{matplotlib},@strong{numpy}, @strong{scipy} python librarys if you wish to use the included plotting scripts. More information can be found at @url{http://scipy.org/getting-started.html}.
@end itemize



@node Invoking GGADT
@chapter Invoking GGADT

@cindex invoking
@cindex options
@cindex usage
@cindex help

To see usage and all available options for @code{ggadt}, simply use the @option{h} option:

@example
ggadt -h
@end example

@section Setting parameter values

The format for running the @command{ggadt} program is:

@example
ggadt @var{option} @dots{}
@end example

With no options, @command{ggadt} runs calculations on a set of default grain parameters. Parameters may be specified as command-line arguments, 

@example
ggadt --parameter=value @dots{}
@end example

or in a parameter file that is specified as a command-line argument,

@example
ggadt --parameter-file-name=/path/to/parameterfile
@end example

or a combination of the two:

@example
ggadt --parameter-file-name=/path/to/parametefile --parameter=value @dots{}
@end example

If a parameter is set by a command-line argument @emph{and} by a parameter file, the command-line argument is used. 

@section Parameter file syntax

The syntax of parameter files is:

@example
#comment
parameter=value
another-parameter=another-value
@dots{}
@end example

@strong{Warning} The @code{cluster-file-name} and @code{euler-file-name} options must be specified with quotes surrounding their values. In order to make the parameter file portable, you should specify an absolute file path, not a relative one.

E.g.:

@example
cluster-file-name='/absolute/path/to/parameter-file.ini'
@end example 

NOT

@example
cluster-file-name=/absolute/path/to/parameter-file.ini
@end example 

or

@example
cluster-file-name='../../parameter-file.ini'
@end example 

Specifying a relative file-path (as in the last example) will work, as long as you always invoke GGADT from the location where the relative file-path is valid. For example, if I am in the parent directory, and my parameter file is in the @code{data/parameter-files} directory, 

@example
cluster-file-name='data/parameter-files/parameter-file.ini'
@end example 

will work, as long as I @strong{always} run @code{ggadt} from the parent directory.

@section Options and parameters


@command{ggadt} supports the following options:

@cindex environment variables, help for

@table @option
@item --help
@itemx -h
@opindex --help
@opindex -h
The `help' screen--prints usage information and available options.

@item --version
@itemx -v
@opindex --version
@opindex -v
Print the version number of GGADT on
standard output and then exit successfully.

@item --parameter-file-name=@var{value}
@opindex --parameter-file-name
Path to a correctly formatted parameter file.

@item --grain-geometry=@var{value}
@opindex --grain-geometry
Geometry of dust grain. Must be one of @code{SPHERE}, @code{ELLIPSOID}, @code{SPHERES}. A @code{SPHERES} grain geometry means that your grain is a conglomerate of smaller spheres. If you wish to use this grain geometry, you should supply a file (hereafter called a ``@emph{cluster file}", see the next option) that defines the relative positions of the spheres that make up the grain. The sizes of these spheres will be normalized so that the effective radius of the grain is consistent with @option{aeff}.  

@item --cluster-file-name=@var{value}
@opindex --cluster-file-name
Path to a correctly formatted cluster file. Several cluster files are included with the distribution (see @file{data/clusters}), and if you wish to create your own, you must mimic exactly the format of these files.

@item --aeff=@var{value}
@opindex --aeff
Effective radius of dust grain. The effective radius is defined to be the radius of a sphere with the same volume as the dust grain.

@item --grain-axis-x=@var{value}
@opindex --grain-axis-x
For @code{ELLIPSOID} grains, we define the lengths of x, y and z axes.

@item --grain-axis-y=@var{value}
@opindex --grain-axis-y

@item --grain-axis-z=@var{value}
@opindex --grain-axis-z

@item --ephot=@var{value}
@opindex --ephot
Energy of the incident X-ray photons in keV.

@item --sed
@opindex --sed
This flag tells GGADT that you would like to calculate the energy-dependent absorption and scattering cross sections. To specify the energy range that you would like the calculation done

@item --nephots=@var{value}
@opindex --nephots
For @code{sed} mode, defines the number of photon energies to calculate the cross sections between @code{--ephot-min} and @code{--ephot-max}

@item --dephot=@var{value}
@opindex --dephot
For @code{sed} mode, defines the energy spacing between different photon energies for which the cross sections are calculated. 

@item --ephot-min=@var{value}
@opindex --ephot-min
For @code{sed} mode, defines the minimum photon energy at which the cross sections are calculated

@item --ephot-max=@var{value}
@opindex --ephot-max
For @code{sed} mode, defines the maximum photon energy at which the cross sections are calculated


@item --ior-re=@var{value}
@opindex --ior-re
The real component of the complex index of refraction, minus one.

@item --ior-im=@var{value}
@opindex --ior-im
The imaginary component of the complex index of refraction.

@item --material=@var{value}
@opindex --material
Specifies the name of the material you're using. Currently, there are no built-in materials in GGADT, so you must use @code{--material='custom'}, and then specify the path to the material file by the @code{--material-file} argument.

@item --material-file=@var{value}
@opindex --material-file
Path to file defining the energy-dependent index of refraction and dielectric constant for the grain material you would like to use. Needs to be formatted in a particular way.


@item --ngrain=@var{value}
@opindex --ngrain
The (square root) of the number of grid elements with which you would like to resolve your grain. To get accurate results out to about 4000 arcseconds, we've found that a value of 64 is good enough.

@item --nscatter=@var{value}
@opindex --nscatter
The (square root) of the number of grid elements with which you would like to resolve the scattering cross section.

@item --norientations=@var{value}
@opindex --norientations
The number of grain orientations relative to the incoming X-ray photon over which to average the differential cross-section.

@item --fftw-optimization=@var{value}
@opindex --fftw-optimization
Must be one of @code{ESTIMATE}, @code{MEASURE}, @code{PATIENT} or @code{EXHAUSTIVE}. FFTW wisdom is saved in @code{$HOME/.ggadt/plans}. For more information about what these tags mean and about FFTW wisdom, see @url{http://fftw.org/fftw3_doc/Words-of-Wisdom_002dSaving-Plans.html#Words-of-Wisdom_002dSaving-Plans}.

@item --euler-angle-mode=@var{value}
@opindex --euler-angle-mode
Must be one of @code{random}, @code{sequential}, or @code{file}. Specifying @code{random} will average over @code{norientations} grain orientations, with each Euler angle chosen from a uniform distribution over [0,2*pi). Specifying @code{sequential} will make GGADT use Euler angles that are separated from each other by a fixed amount. Specifying @code{file} allows you to give GGADT specific Euler angles to use in orientational averaging. The @code{file} mode requires that you also specify @code{--euler-angle-file=/path/to/euler-file} which contains a list of Euler angles.

@item --euler-angle-file=@var{value}
@opindex --euler-angle-file
Path to a file containing a list of Euler angles which GGADT will use to compute orientational averages. Only used when @code{--euler-angle-mode=file}.

@item --rotation-axis=@var{value}
@opindex --rotation-axis
Must be one of @code{none}, @code{xaxis}, @code{yaxis}, or @code{zaxis}. If not @code{none}, this will average over all orientations about the specified principle axis. Useful for grains that are aligned, for instance, with a magnetic field.

@item --use-padded-fft
@itemx -s
@opindex --use-padded-fft
@opindex -s 
This will force GGADT to do only one FFT. In order to provide you with the desired angular resolution of the differential cross section (set by @code{nscatter}), GGADT will pad the 2-d grid on which the shadow function is defined. Forcing GGADT to use a padded FFT, instead of the more efficient method without padding, will run much slower.



@end table

@section The scattering mode versus the @code{sed} mode
By default, GGADT will determine the orientation-averaged differential scattering cross section for your grain. If, instead, you wish to calculate the absorption and (total) scattering cross sections of the grain as a function of energy, add the @code{--sed} flag to the command line arguments. The additional command line arguments that are relevant for the ``sed" mode are:

@table @option
@item @code{--dephot} (or @code{--nephots})
@item @code{--ephot-min}
@item @code{--ephot-max}
@item @code{--material}: this MUST be specified as @code{--material='custom'} for the time being. In the future, we'll hard-code some materials into the program so the user doesn't have to lug around a set of text files that define the energy-dependent dielectric constant for common materials.
@item @code{--material-file}
@end table

@subsection Materials and material files

The material files must be formatted in the way that GGADT expects, namely with a header of:

@example
17 =ICOMP: amorphous olivine-like astrosilicate
    E(eV)      Re(n)-1    Im(n)    Re(eps)-1  Im(eps)
@end example

followed by material values:

@example
1.000000E-05  2.435E+00 1.119E-03  1.080E+01 7.688E-03
1.240000E-05  2.435E+00 1.388E-03  1.080E+01 9.534E-03
1.771000E-05  2.435E+00 1.982E-03  1.080E+01 1.362E-02
2.000000E-05  2.435E+00 2.239E-03  1.080E+01 1.538E-02
@dots{}
@end example

@strong{Future goals} : 
@itemize
@item Allow for multiple grain compositions at once
@item Allow for the user to specify different types of mixed compositions (layers, inclusions, solid spheroidal cores with no porosity, user-defined, etc.). Suggestions for improvement and utility are very welcome.
@item Allow a user-defined set of energies to calculate the cross sections
@end itemize

@section Getting the accuracy you want


@subsection Differential scattering cross section calculations 

GGADT solves for either the differential scattering cross section as a function of scattering angle, or the total scattering and absorption cross sections as a function of photon energy, and must do so on a 2D numerical grid. The accuracy of the solution provided by GGADT depends on the resolution of these grids. In the case where the grain is non-spherical, the accuracy also depends on the number of orientations over which the calculation is averaged.

The input parameters that determine accuracy are:

@itemize
@item @code{ngrain} -- The number of grid elements (along one dimension) for which the grain is defined.
@item @code{nscatter} (or equivalently @code{dtheta}) -- The number of grid points - along one dimension - over which the differential cross section is defined, or, if using @code{dtheta}, the width of the grid elements (in arcseconds).
@item @code{norientations} -- The number of grain orientations over which to average the calculation.
@end itemize

We've done some sample runs for a spherical grain,

@image{RMS_ngrain_nscatter,5in,5in}

@subsection Scattering and absorption cross-section calculations 

Accuracy results for TOTAL cross section calculations to come soon...



@node Example usage
@chapter Example usage

@cindex sample output
@cindex examples
@section Default case

If you simply want to test that @code{ggadt} is running properly, you can simply do

@example
src/ggadt
@end example

From the parent directory. This will solve a test case, which is defined by the following hard-coded default parameters:

@example
aeff           = 0.2
ephot          = 2.0
grain-axis-x   = 1.0
grain-axis-y   = 1.0
grain-axis-z   = 1.0
ior-re         = -1.920E-4
ior-im         = 2.807E-5
grain-geometry = 'sphere'
euler-angle-mode = 'random'
euler-angle-file = ''
ngrain         = 256
nscatter       = 100
norientations  = 100
dtheta         = 10.0
max-angle      = 3000.
cluster-file-name = ''
fftw-optimization = 'estimate'
@end example

If you would like to plot the output of this code, pipe the standard output of @code{ggadt} to a file of your choice. Then run the python plotting scripts:

@example

src/ggadt > output.dat
python scripts/plot.py output.dat

@end example

This will display two plots. One plot shows the full 2D cross-scattering efficiency. The other shows: (1) a phi-averaged plot of the differential cross-section efficiency (2) a slice of the full 2D grid at phi=0.0 and phi = pi/2 (3) the one-sigma RMS fluctuations over phi (in light green) and the max/min values over phi (in light grey).

@section Using @code{make_sample_plots.py}
We have made a small python script (@code{scripts/make_sample_plots.py}) that runs example cases for different grain geometries. You will need the matplotlib, numpy and scipy libraries in order to run this script. More information about these libaries is available at @url{http://scipy.org/getting-started.html}.

The python script runs GGADT for a grain with an effective radius of 0.2 microns, composed of MgFeSiO_4 silicate, with an incident photon energy of 2.0 keV, and with @code{ngrain} of 256 and a @code{nscatter} of 100. 

The inset within the plot, on the upper left corner, shows the full 2d grid of the scattering cross section efficiency.

@image{sample-sphere,5in,5in}

@image{sample-ellipsoid,5in,5in}

@image{sample-spheres,5in,5in}

@section Ellipsoids and spheroids
GGADT allows you to specify a general, ellipsoidal (tri-axial) grain through the input options @code{--grain-axis-x,y,z=}@emph{val}. These specify the relative lengths of the three principal axes of the grain. These axes lengths are then normalized so that the effective radius of the grain is consistent with the @code{--aeff} parameter.

@subsection Orientational averages about a principal axis

If you wish to calculate orientationally-averaged quantities of a grain @emph{about a principal axis}, GGADT allows you to do this through specifying @code{--rotation-axis=xaxis,yaxis,zaxis,none}. The @code{--rotation-axis} parameter is 'none' by default.

@subsubsection Coordinate systems

The @code{--rotation-axis} parameter will work for grain agglomerates as well. The positions of the agglomerates as specified in the agglomerate file define the coordinate system that GGADT works in. Be sure the axis you specify via @code{--rotation-axis} is really the axis you want. You'll have to know something about how the coordinate system of the agglomerate file is defined.

If you are using an @code{ELLIPSOID} grain geometry, the coordinate system is such that the z-axis points towards the observer (i.e. the incident photons' direction of propagation), and the x and y directions are defined by the @code{--grain-axis-x,y,z} input parameters. 

Currently, there is no option to specify a custom rotation axis about which to orient the grain. If this is something you would like added to GGADT, let John Hoffman know.

@subsubsection Example runs for a prolate spheroid

Below are the results from running GGADT on a prolate spheroid (with axes ratios 2:1:1), with the grain's x-axis being the longest.

@strong{Orientation-averaged differential scattering efficiency about the x-axis}
@example
src/ggadt --grain-axis-y=0.5 --grain-axis-z=0.5 --grain-geometry=ellipsoid --rotation-axis=xaxis > outputx.dat
python scripts/plot.py outputx.dat
@end example
@image{spheroid_rot_xaxis,5in,5in}

@strong{Orientation-averaged differential scattering efficiency about the y-axis}
@example
src/ggadt --grain-axis-y=0.5 --grain-axis-z=0.5 --grain-geometry=ellipsoid --rotation-axis=yaxis > outputy.dat
python scripts/plot.py outputy.dat
@end example
@image{spheroid_rot_yaxis,5in,5in}

@strong{Orientation-averaged differential scattering efficiency about the z-axis}
@example
src/ggadt --grain-axis-y=0.5 --grain-axis-z=0.5 --grain-geometry=ellipsoid --rotation-axis=zaxis > outputz.dat
python scripts/plot.py outputz.dat
@end example
@image{spheroid_rot_zaxis,5in,5in}

@node Testing against previous results
@chapter Testing against previous results

@section Spherical case (ADT/Mie theory)
@subsection GGADT
@image{DA06_f1_spheres,4in,4in}
@subsection Actual (Figure 1) from Draine & Allaf-Akbari 2006
@image{da06_spheres_actual,3in,3in}

@section Ellipsoidal case (Draine and Allaf-Akbari 2006)

@subsection GGADT
@image{DA06_f2_ellipsoids,3in,3in}

@subsection Actual (Figure 2) from Draine & Allaf-Akbari 2006
@image{da06_ellipsoids_actual,4in,4in}

@section Agglomeration of spheres (Heng & Draine 2009)

@image{HD09_f3,5in,5in}
@node FFT comparison
@chapter FFT comparison
@strong{FFTW3 NOT supported in current version}: There is currently NO support for FFTW3 at the moment. The FFTW module needs to be reverted to the Fortran 95 standard. At this time, it's not a huge priority. GGADT works just fine, and does not require you to install an external library. Future versions of GGADT will likely include FFTW3 support.

Currently, GGADT allows you to choose between two FFT algorithms: FFTW 3 (@url{http://fftw.org/}), which requires you install the FFTW3 library, and GPFA (Generalized Prime Factor Algorithm)@footnote{Temperton, C. (1992). A Generalized Prime Factor FFT Algorithm for any N=2^p3^q5^r. SIAM Journal on Scientific and Statistical Computing, 13(3), 676-686.}, which is self-contained and included with the GGADT package. GPFA is used by default, and, as shown below, is slightly faster than FFTW in the current version of GGADT. This will change in later versions, since at the moment, we do not take advantage of saving and loading FFTW "wisdom". 

Earlier versions of GGADT, which did FFT's in a different way (only did padded FFT's, but utilized FFTW wisdom), had FFTW being about 20 percent faster than GPFA.

If you wish to use the FFTW3 version of GGADT, you will need to install FFTW 3.3.x (we have only tested 3.3.3, but GGADT should in principal be compatible with all 3.x.x versions). GPFA will not currently work with FFTW 2.x, as the two interfaces are different, but plans to include FFTW 2.x support are in the works. 

If you have a particular FFT library that you would like to see implemented, please send an e-mail to jah5 (at) princeton.edu. It will likely be faster if you simply write your own module to attach to GGADT. This module must provide the function @code{fft_firstk(arr,K)} where @code{arr} is an N by N array, and @code{K} is an integer less than N. The function must return a @code{K} by @code{K} array, containing the first @code{K} values of the FFT of @code{arr}. The complexity of this algorithm should scale as (N*N)log(@code{K}*@code{K}), instead of the (N*N)log(N*N) complexity of the standard two-dimensional FFT.

For information about how to construct this algorithm, see the instructions for FFTW at @url{http://www.fftw.org/pruned.html}.

If you are successful at porting your FFT algorithm, let us know, and we will do our best to test it and include it with future releases.

@section Timing
@image{timing_actual_time,5in,5in}
@image{timing_relative_to_gpfa,5in,5in}

@node GNU Free Documentation License
@appendix GNU Free Documentation License

@include fdl.texi


@node Concept index
@unnumbered Concept index

@printindex cp

@bye
