parent_dir = "/Users/jah5/Desktop/Draine_temp/GGADT_JohnsMac/ggadt"
paramfile_dir = parent_dir + "/data/parameter-files"
data_dir = parent_dir + "/data"
ggadt = parent_dir + "/src/ggadt"
script_dir = parent_dir+"/scripts"
cluster_dir = data_dir+"/clusters"
